"""create_uploaded_files_table

Revision ID: 34cb4c7d4a37
Revises: 20260602_0001
Create Date: 2026-06-10 16:44:56.553282
"""
from alembic import op
import sqlalchemy as sa


revision = '34cb4c7d4a37'
down_revision = '20260602_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_backend', sa.String(length=50), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('public_url', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
