"""align_schemas_to_latest_doc

Revision ID: 4314465edd6b
Revises: ff76ff7e99ce
Create Date: 2026-06-17 13:41:22.338997
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4314465edd6b'
down_revision = 'ff76ff7e99ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributors',
        sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('distributor_type', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.add_column('batch_tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('batch_tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('batch_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using="id::bigint")
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using="session_id::bigint")
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using="id::bigint")
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('detect_records', sa.Column('distributor_id', sa.BigInteger(), nullable=True))
    op.add_column('detect_records', sa.Column('adoption_status', sa.String(length=20), nullable=False))
    op.alter_column('detect_records', 'serial_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('detect_records', 'device_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('detect_records', 'fault_category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('detect_records', 'fault_subtype',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('detect_records', 'verdict',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('detect_records', 'issue_detected',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True,
               postgresql_using="CASE WHEN issue_detected IS TRUE THEN 'Issue Detected' WHEN issue_detected IS FALSE THEN 'no issue' ELSE NULL END")
    op.alter_column('detect_records', 'reject_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_detect_records_distributor_id'), 'detect_records', ['distributor_id'], unique=False)
    op.create_foreign_key(None, 'detect_records', 'distributors', ['distributor_id'], ['id'])
    op.drop_column('detect_records', 'feedback_status')
    op.add_column('thresholds', sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('thresholds', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('thresholds', 'is_hidden')
    op.drop_column('thresholds', 'config')
    op.add_column('uploaded_files', sa.Column('detectRecordID', sa.BigInteger(), nullable=True))
    op.alter_column('uploaded_files', 'id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using="id::bigint")
    op.alter_column('uploaded_files', 'filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'storage_backend',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'public_url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_foreign_key(None, 'uploaded_files', 'detect_records', ['detectRecordID'], ['id'])
    op.add_column('users', sa.Column('distributor_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.alter_column('users', 'distributor_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_distributor_id'), 'users', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'distributors', ['distributor_id'], ['id'])
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_distributor_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'distributor_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    op.drop_column('users', 'distributor_id')
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.alter_column('uploaded_files', 'public_url',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'storage_backend',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'filename',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using="id::varchar")
    op.drop_column('uploaded_files', 'detectRecordID')
    op.add_column('thresholds', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('thresholds', sa.Column('is_hidden', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('thresholds', 'is_deleted')
    op.drop_column('thresholds', 'config_json')
    op.add_column('detect_records', sa.Column('feedback_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'detect_records', type_='foreignkey')
    op.drop_index(op.f('ix_detect_records_distributor_id'), table_name='detect_records')
    op.alter_column('detect_records', 'reject_reason',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('detect_records', 'issue_detected',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               postgresql_using="CASE WHEN issue_detected = 'Issue Detected' THEN TRUE ELSE FALSE END")
    op.alter_column('detect_records', 'verdict',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('detect_records', 'fault_subtype',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('detect_records', 'fault_category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('detect_records', 'device_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('detect_records', 'serial_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('detect_records', 'adoption_status')
    op.drop_column('detect_records', 'distributor_id')
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using="id::varchar")
    op.alter_column('chat_messages', 'role',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using="session_id::varchar")
    op.alter_column('chat_messages', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using="id::varchar")
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.alter_column('batch_tasks', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('batch_tasks', 'completed_at')
    op.drop_column('batch_tasks', 'started_at')
    op.drop_table('distributors')
    # ### end Alembic commands ###
