"""drop_derivable_upload_fields

Revision ID: 5846104e7e83
Revises: 42bbddb8c3d8
Create Date: 2026-06-18 09:23:54.752553
"""
from alembic import op
import sqlalchemy as sa


revision = '5846104e7e83'
down_revision = '42bbddb8c3d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'public_url')
    op.drop_column('uploaded_files', 'mime_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('uploaded_files', sa.Column('public_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
