"""increase_reject_reason_length

Revision ID: a00c63e96695
Revises: 5846104e7e83
Create Date: 2026-06-18 11:24:43.357007
"""
from alembic import op
import sqlalchemy as sa


revision = 'a00c63e96695'
down_revision = '5846104e7e83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detect_records', 'reject_reason',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detect_records', 'reject_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
