"""add_adopted_at_to_detect_records

Revision ID: ff76ff7e99ce
Revises: 20260611_0003
Create Date: 2026-06-17 09:55:32.564975
"""
from alembic import op
import sqlalchemy as sa


revision = 'ff76ff7e99ce'
down_revision = '20260611_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detect_records', sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detect_records', 'adopted_at')
    # ### end Alembic commands ###
